language: node_js
sudo: true
node_js:
  - "6.0"
  - "5.0"
  - "4.4"
  - "4.3"
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "iojs"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq golang
  - mkdir -p $HOME/go_workspace
  - export GOPATH=$HOME/go_workspace
  - go get -u github.com/gopherjs/gopherjs
  - npm install -g npm
